REGIONS = [
    "서울", "경기", "강원", "광주", "인천", "대구", "부산",
    "대전", "울산", "세종", "충북", "충남", "전북", "전남",
    "경북", "경남", "제주",
    "서울특별시", "경기도", "강원특별자치도", "광주광역시",
    "인천광역시", "대구광역시", "부산광역시", "대전광역시",
    "울산광역시", "세종특별자치시", "충청북도", "충청남도",
    "전라북도", "전라남도", "경상북도", "경상남도", "제주특별자치도",
]

ALL_FLOWERS = [
    "튤립", "프리지아", "라넌큘러스", "수선화", "히아신스", "조팝나무",
    "아카시아", "무스카리", "아네모네", "아이리스", "작약", "라일락",
    "스위트피", "칼라", "은방울꽃", "해바라기", "장미", "백합", "델피늄",
    "리시안셔스", "안개꽃", "글라디올러스", "안스리움", "거베라", "천일홍",
    "글로리오사", "수국", "알스트로메리아", "칼랑코에", "지니아", "아마릴리스",
    "베고니아", "국화", "소국", "코스모스", "다알리아", "핑크뮬리", "팜파스",
    "용담", "에린지움", "아스트란시아", "메리골드", "아스터", "셀로시아",
    "포인세티아", "목화", "스토크", "시클라멘", "심비디움", "카네이션",
    "낙산홍", "스노우드롭", "헬레보루스", "왁스플라워",
]

REGION_MAP = {
    "서울": "SEOUL", "경기": "GYEONGGI", "강원": "GANGWON",
    "광주": "GWANGJU", "인천": "INCHEON", "대구": "DAEGU",
    "부산": "BUSAN", "대전": "DAEJEON", "울산": "ULSAN",
    "세종": "SEJONG", "충북": "CHUNGBUK", "충청북도": "CHUNGBUK",
    "충남": "CHUNGNAM", "충청남도": "CHUNGNAM",
    "전북": "JEONBUK", "전라북도": "JEONBUK",
    "전남": "JEONNAM", "전라남도": "JEONNAM",
    "경북": "GYEONGBUK", "경상북도": "GYEONGBUK",
    "경남": "GYEONGNAM", "경상남도": "GYEONGNAM",
    "제주": "JEJU",
    "서울특별시": "SEOUL", "경기도": "GYEONGGI",
    "강원특별자치도": "GANGWON", "광주광역시": "GWANGJU",
    "인천광역시": "INCHEON", "대구광역시": "DAEGU",
    "부산광역시": "BUSAN", "대전광역시": "DAEJEON",
    "울산광역시": "ULSAN", "세종특별자치시": "SEJONG",
    "제주특별자치도": "JEJU",
}

NEARBY_REGIONS = {
    "SEOUL": ["GYEONGGI", "INCHEON"],
    "GYEONGGI": ["SEOUL", "INCHEON", "GANGWON", "CHUNGNAM", "CHUNGBUK"],
    "INCHEON": ["SEOUL", "GYEONGGI"],
    "GANGWON": ["GYEONGGI", "CHUNGBUK", "GYEONGBUK"],
    "DAEJEON": ["CHUNGNAM", "CHUNGBUK", "GYEONGBUK", "GYEONGNAM"],
    "CHUNGBUK": ["GYEONGGI", "GANGWON", "DAEJEON", "CHUNGNAM"],
    "CHUNGNAM": ["GYEONGGI", "DAEJEON", "CHUNGBUK", "JEONBUK"],
    "GWANGJU": ["JEONNAM", "JEONBUK"],
    "JEONBUK": ["CHUNGNAM", "GWANGJU", "JEONNAM", "GYEONGNAM"],
    "JEONNAM": ["GWANGJU", "JEONBUK", "GYEONGNAM"],
    "DAEGU": ["GYEONGBUK", "GYEONGNAM"],
    "GYEONGBUK": ["DAEGU", "GANGWON", "CHUNGBUK", "GYEONGNAM"],
    "GYEONGNAM": ["DAEGU", "BUSAN", "ULSAN", "JEONNAM"],
    "BUSAN": ["GYEONGNAM", "ULSAN"],
    "ULSAN": ["BUSAN", "GYEONGNAM", "GYEONGBUK"],
    "SEJONG": ["DAEJEON", "CHUNGNAM", "CHUNGBUK"],
    "JEJU": [],
}
