from .agent_prompts import (
    FLORAL_ANALYST_ROLE, FLORAL_ANALYST_GOAL, FLORAL_ANALYST_BACKSTORY,
    BOUQUET_STYLIST_ROLE, BOUQUET_STYLIST_GOAL, BOUQUET_STYLIST_BACKSTORY,
    LOCAL_SHOP_MATCHER_ROLE, LOCAL_SHOP_MATCHER_GOAL, LOCAL_SHOP_MATCHER_BACKSTORY,
    LOCATION_PARSER_ROLE, LOCATION_PARSER_GOAL, LOCATION_PARSER_BACKSTORY,
)
from .task_prompts import (
    _flower_analysis_description, _FLOWER_ANALYSIS_EXPECTED_OUTPUT,
    _BOUQUET_STYLING_DESCRIPTION, _BOUQUET_STYLING_EXPECTED_OUTPUT,
    _shop_matching_description, _SHOP_MATCHING_EXPECTED_OUTPUT,
    _location_parsing_description, _LOCATION_PARSING_EXPECTED_OUTPUT,
)

FLORAL_ANALYST_PROMPTS = {
    "role": FLORAL_ANALYST_ROLE,
    "goal": FLORAL_ANALYST_GOAL,
    "backstory": FLORAL_ANALYST_BACKSTORY,
}
BOUQUET_STYLING_PROMPTS = {
    "role": BOUQUET_STYLIST_ROLE,
    "goal": BOUQUET_STYLIST_GOAL,
    "backstory": BOUQUET_STYLIST_BACKSTORY,
}
LOCAL_SHOP_MATCHER_PROMPTS = {
    "role": LOCAL_SHOP_MATCHER_ROLE,
    "goal": LOCAL_SHOP_MATCHER_GOAL,
    "backstory": LOCAL_SHOP_MATCHER_BACKSTORY,
}
LOCATION_PARSER_PROMPTS = {
    "role": LOCATION_PARSER_ROLE,
    "goal": LOCATION_PARSER_GOAL,
    "backstory": LOCATION_PARSER_BACKSTORY,
}

FLORAL_ANALYST_TASK_PROMPTS = {
    "description": _flower_analysis_description,
    "expected_output": _FLOWER_ANALYSIS_EXPECTED_OUTPUT,
}
BOUQUET_STYLING_TASK_PROMPTS = {
    "description": _BOUQUET_STYLING_DESCRIPTION,
    "expected_output": _BOUQUET_STYLING_EXPECTED_OUTPUT,
}
SHOP_MATCHING_TASK_PROMPTS = {
    "description": _shop_matching_description,
    "expected_output": _SHOP_MATCHING_EXPECTED_OUTPUT,
}
LOCATION_PARSING_TASK_PROMPTS = {
    "description": _location_parsing_description,
    "expected_output": _LOCATION_PARSING_EXPECTED_OUTPUT,
}
