from .agent_prompts import FLORAL_ANALYST_ROLE, FLORAL_ANALYST_GOAL, FLORAL_ANALYST_BACKSTORY, BOUQUET_STYLIST_ROLE, BOUQUET_STYLIST_GOAL, BOUQUET_STYLIST_BACKSTORY, LOCAL_SHOP_MATCHER_ROLE, LOCAL_SHOP_MATCHER_GOAL, LOCAL_SHOP_MATCHER_BACKSTORY
from .task_prompts import  flower_analysis_description, FLOWER_ANALYSIS_EXPECTED_OUTPUT, BOUQUET_STYLING_DESCRIPTION, BOUQUET_STYLING_EXPECTED_OUTPUT, shop_matching_description, SHOP_MATCHING_EXPECTED_OUTPUT

FLORAL_ANALYST_PROMPTS = {
    "role": FLORAL_ANALYST_ROLE,
    "goal": FLORAL_ANALYST_GOAL,
    "backstory": FLORAL_ANALYST_BACKSTORY,
}
BOUQUET_STYLING_PROMPTS = {
    "role": BOUQUET_STYLIST_ROLE,
    "goal": BOUQUET_STYLIST_GOAL,
    "backstory": BOUQUET_STYLIST_BACKSTORY,
}
LOCAL_SHOP_MATCHER_PROMPTS = {
    "role": LOCAL_SHOP_MATCHER_ROLE,
    "goal": LOCAL_SHOP_MATCHER_GOAL,
    "backstory": LOCAL_SHOP_MATCHER_BACKSTORY,
}


FLORAL_ANALYST_TASK_PROMPTS = {
    "description": flower_analysis_description,
    "expected_output": FLOWER_ANALYSIS_EXPECTED_OUTPUT,
}

BOUQUET_STYLING_TASK_PROMPTS = {
    "description": BOUQUET_STYLING_DESCRIPTION,
    "expected_output": BOUQUET_STYLING_EXPECTED_OUTPUT,
}

SHOP_MATCHING_TASK_PROMPTS = {
    "description": shop_matching_description,
    "expected_output": SHOP_MATCHING_EXPECTED_OUTPUT,
}